[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "themodel"
version = "1.0.0"
description = "A python package that takes your boring b&W manga and colorises it."

requires-python = ">=3.7"
dependencies = [
    
]